name : My Linter Action

on :
  
  push :
    branches : [ main ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps :
      
      - uses : actions/checkout@v2

      - name: Exécuter un script
        run: echo Hello, World !

      - name : Exécuter le service de linting
        uses : github/super-linter@v3Test de tout le code
